### ISSUE TITLE
Update to 20240324 git

### ISSUE THREAD

**Issue by Icenowy** [cwt-lpi4a/xf86-video-thead#1]
I did some change on xf86-video-thead that fixes PRESENT extension. 

BTW do you want to import my GLVNDizd mesa-pvr from https://github.com/Icenowy/aosc-os-pvr/tree/master/ddk117/mesa-ddk117 ? This will allow coexistence with a normal mesa.

**Comment by cwt** [comment]
Great to know, I will build a new release asap.

**Comment by cwt** [comment]
rebuilt as https://github.com/cwt-lpi4a/xf86-video-thead/commit/58543099188e38cb6c14b3563605d0ab66813552
